"""comments2

Revision ID: 952ec3e17db1
Revises: 1cbac099fe6d
Create Date: 2023-09-12 00:56:45.455712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952ec3e17db1'
down_revision = '1cbac099fe6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('comment_content',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('comment_content',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
